---
title: "Table 1"
author: "Sashank"
date: "7/10/2019"
output: html_document
---

```{r}
library(irr)
library(psych)
library(readxl)
```

```{r}
LS_read_ratings <- read_excel("Likert Scale/all_completed_cleaned_modified.xlsx", sheet = "read_rank_all")
LS_coh_ratings <- read_excel("Likert Scale/all_completed_cleaned_modified.xlsx", sheet = "cohe_rank_all")
```

```{r}
#Fleiss
kappam.fleiss(LS_read_ratings)
kappam.fleiss(LS_coh_ratings)
```
```{r}
#Krippendorff
kripp.alpha(t(LS_read_ratings), method="ordinal")
kripp.alpha(t(LS_coh_ratings), method="ordinal")
```

```{r}
#ICC
ICC(LS_read_ratings)
ICC(LS_coh_ratings)
```

```{r}
icc(LS_read_ratings, model="twoway", type="consistency",unit="a")
icc(LS_coh_ratings, model="twoway", type="consistency",unit="a")
```

```{r}
icc(LS_read_ratings, model="twoway", type="agreement",unit="a")
icc(LS_coh_ratings, model="twoway", type="agreement",unit="a")
```

```{r}
RME_read_ratings <- read_excel("RME/all_completed_modified.xlsx", sheet = "read_rank_all")
RME_coh_ratings <- read_excel("RME/all_completed_modified.xlsx", sheet = "cohe_rank_all")

```

```{r}
#Fleiss
kappam.fleiss(RME_read_ratings)
kappam.fleiss(RME_coh_ratings)
```
```{r}
#Krippendorff
kripp.alpha(t(RME_read_ratings), method="ordinal")
kripp.alpha(t(RME_coh_ratings), method="ordinal")
```

```{r}
#ICC
ICC(RME_read_ratings)
ICC(RME_coh_ratings)
```

```{r}
icc(RME_read_ratings, model="twoway", type="consistency",unit="a")
icc(RME_coh_ratings, model="twoway", type="consistency",unit="a")
```

```{r}
icc(RME_read_ratings, model="twoway", type="agreement",unit="a")
icc(RME_coh_ratings, model="twoway", type="agreement",unit="a")
```
```{r}
BME_read_ratings <- read_excel("BME/all_completed_modified.xlsx", sheet = "read_rank_all")
BME_coh_ratings <- read_excel("BME/all_completed_modified.xlsx", sheet = "cohe_rank_all")

```

```{r}
#Fleiss
kappam.fleiss(BME_read_ratings)
kappam.fleiss(BME_coh_ratings)
```
```{r}
#Krippendorff
kripp.alpha(t(BME_read_ratings), method="ordinal")
kripp.alpha(t(BME_coh_ratings), method="ordinal")
```

```{r}
#ICC
ICC(BME_read_ratings)
ICC(BME_coh_ratings)
```
```{r}
icc(BME_read_ratings, model="twoway", type="consistency",unit="a")
icc(BME_coh_ratings, model="twoway", type="consistency",unit="a")
```
```{r}
icc(BME_read_ratings, model="twoway", type="agreement",unit="a")
icc(BME_coh_ratings, model="twoway", type="agreement",unit="a")
```
```{r}
RR_read_ratings <- read_excel("RR/all_completed_modified.xlsx", sheet = "read_rank_all")
RR_coh_ratings <- read_excel("RR/all_completed_modified.xlsx", sheet = "cohe_rank_all")
```

```{r}
#Fleiss
kappam.fleiss(RR_read_ratings)
kappam.fleiss(RR_coh_ratings)
```
```{r}
#Krippendorff
kripp.alpha(t(RR_read_ratings), method="ordinal")
kripp.alpha(t(RR_coh_ratings), method="ordinal")
```

```{r}
#ICC
ICC(RR_read_ratings)
ICC(RR_coh_ratings)
```

```{r}
icc(RR_read_ratings, model="twoway", type="consistency",unit="a")
icc(RR_coh_ratings, model="twoway", type="consistency",unit="a")
```

```{r}
icc(RR_read_ratings, model="twoway", type="agreement",unit="a")
icc(RR_coh_ratings, model="twoway", type="agreement",unit="a")
```

